### ISSUE TITLE
OOOps!

### ISSUE THREAD

**Issue by the-teacher** [aleksposte/typograf#6]
Мы делаем компоненту для Rails а не рельсовое приложение.

В задании четко укзано - создать руби скрипт. Ты сделал что то другое.
В репе у тебя должно быть 2 файла `my_srcipt.rb` и `README`
в крайнем случае папка с текстовыми файлами для проверки типографа

**Comment by aleksposte** [comment]
Это я по инерции(( прошу прощения

**Comment by the-teacher** [comment]
@aleksposte после удаления лишнего закрой задачу.

**Comment by aleksposte** [comment]
лишнее удалил
