### ISSUE TITLE
Install node. WHAT?

### ISSUE THREAD

**Issue by the-teacher** [aleksposte/typograf#7]
``` sh
git clone --depth 1 https://github.com/nodejs/node
cd node
export JOBS=2 # optional, sets number of parallel commands.
mkdir ~/local
./configure --prefix=$HOME/local/node
make
make install
export PATH=$HOME/local/node/bin:$PATH
```

Не, ну круто канешн. Только давай подумаем о том, том, кто будет читать твой ридми и пользоваться им.

если мы говорим про начальную стадию. И готовы пренебречь всеми платформами. То давай так.

http://brew.sh

```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install node

node -v
```

и вообще я крайне опасаюсь за `make install`. почему не `checkinstall` ? он же на маке тоже доступен, не?

**Comment by aleksposte** [comment]
Привет, в большей степени пока readme для меня самого, очередность выполнения и наглядность. (я уберу в дальнейшем ненужное). установку на другие платформы - добавлю. Про brew понял, исправлю.

**Comment by aleksposte** [comment]
Спасибо за checkinstall, как то не пользовался, почитал, это более правильный вариант.

**Comment by the-teacher** [comment]
@aleksposte `readme для меня самого` сразу с этой финей завязывай. Сразу! Ты работаешь не для себя. забудь об этом. Я твой заказчик. Я твой самый любимый и самый строгий пользователь. Ты должен сразу делать все так, что бы было удобно другому, а не тебе.

Испытывай боль. Заставляй свой мозг, руки и голову работать на хороший результат сразу. Время черновичков и поделок для тебя закончилось.

**Comment by the-teacher** [comment]
@aleksposte `Спасибо за checkinstall`. Пожалуйста.

**Comment by aleksposte** [comment]
readme - лишнее убрал, про заказчика понял, постараюсь делать удобно.

**Comment by the-teacher** [comment]
@aleksposte в ридми можно (и нужно) разбивать на логически блоки текста.
Вообще ридми для приличного продукта - 95% успеха.

```
Сделай 
```

```
вот так
```

```
и будет совсем здорово
```

Куски блоков в markdown оформляются через так  https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

чуть подчисти ридми и закрывай задачу

**Comment by aleksposte** [comment]
Подкорректировал. Надеюсь получилось удобно для восприятия.
